using System.Security.Claims;using DadoHome.Api.Data;using Microsoft.EntityFrameworkCore;
namespace DadoHome.Api.Auth;
public record StaffCreateRequest(string Name,string Phone,string Role,string Password);
public record StaffUpdateRequest(string Name,string Phone,string Role,bool IsActive,string? Password);
public static class StaffManagement{
 static readonly string[] StaffRoles=[Roles.Administrator,Roles.OrderManager,Roles.Finance,Roles.Support,Roles.Cashier];
 static bool ValidRole(string role)=>StaffRoles.Contains(role,StringComparer.Ordinal);
 static Guid? UserId(ClaimsPrincipal u)=>Guid.TryParse(u.FindFirstValue(ClaimTypes.NameIdentifier)??u.FindFirstValue("sub"),out var id)?id:null;
 public static void MapStaffManagement(this WebApplication app){
  app.MapGet("/api/admin/staff",async(DadoDbContext db)=>await db.StaffUsers.AsNoTracking().OrderBy(x=>x.Name).Select(x=>new{x.Id,x.Name,x.Phone,x.Role,x.IsActive,x.CreatedAt}).ToListAsync()).RequireAuthorization(p=>p.RequireRole(Roles.Administrator));
  app.MapPost("/api/admin/staff",async(StaffCreateRequest r,ClaimsPrincipal user,DadoDbContext db,PasswordService passwords)=>{if(string.IsNullOrWhiteSpace(r.Name)||string.IsNullOrWhiteSpace(r.Phone)||r.Phone.Length>64||string.IsNullOrWhiteSpace(r.Password)||r.Password.Length<10||r.Password.Length>1024||!ValidRole(r.Role))return Results.BadRequest(new{error="InvalidStaffData"});var phone=r.Phone.Trim();if(await db.StaffUsers.AnyAsync(x=>x.Phone==phone))return Results.Conflict(new{error="PhoneAlreadyExists"});var s=new StaffUser{Id=Guid.NewGuid(),Name=r.Name.Trim(),Phone=phone,Role=r.Role,PasswordHash=passwords.Hash(r.Password),IsActive=true};db.StaffUsers.Add(s);db.AuditLogs.Add(new AuditLog{Id=Guid.NewGuid(),ActorId=UserId(user)?.ToString()??"staff",Role=Roles.Administrator,Action="STAFF_CREATED",Entity="StaffUser",EntityId=s.Id.ToString()});await db.SaveChangesAsync();return Results.Created($"/api/admin/staff/{s.Id}",new{s.Id,s.Name,s.Phone,s.Role,s.IsActive,s.CreatedAt});}).RequireAuthorization(p=>p.RequireRole(Roles.Administrator));
  app.MapPut("/api/admin/staff/{id:guid}",async(Guid id,StaffUpdateRequest r,ClaimsPrincipal user,DadoDbContext db,PasswordService passwords)=>{await using var tx=await db.Database.BeginTransactionAsync();await db.Database.ExecuteSqlRawAsync("SELECT pg_advisory_xact_lock(7110241100)");var s=await db.StaffUsers.SingleOrDefaultAsync(x=>x.Id==id);if(s is null)return Results.NotFound();if(string.IsNullOrWhiteSpace(r.Name)||string.IsNullOrWhiteSpace(r.Phone)||r.Phone.Length>64||!ValidRole(r.Role)||(r.Password is not null&&r.Password.Length>0&&(r.Password.Length<10||r.Password.Length>1024)))return Results.BadRequest(new{error="InvalidStaffData"});var phone=r.Phone.Trim();if(await db.StaffUsers.AnyAsync(x=>x.Phone==phone&&x.Id!=id))return Results.Conflict(new{error="PhoneAlreadyExists"});var actor=UserId(user);if(actor==id&&!r.IsActive)return Results.Conflict(new{error="CannotDeactivateSelf"});if(s.Role==Roles.Administrator&&(r.Role!=Roles.Administrator||!r.IsActive)&&await db.StaffUsers.CountAsync(x=>x.Role==Roles.Administrator&&x.IsActive)==1)return Results.Conflict(new{error="LastAdministrator"});if(s.Role!=r.Role||s.IsActive!=r.IsActive||!string.IsNullOrWhiteSpace(r.Password))s.AuthVersion++;s.Name=r.Name.Trim();s.Phone=phone;s.Role=r.Role;s.IsActive=r.IsActive;if(!string.IsNullOrWhiteSpace(r.Password)){s.PasswordHash=passwords.Hash(r.Password);s.FailedLoginCount=0;s.LockedUntil=null;}db.AuditLogs.Add(new AuditLog{Id=Guid.NewGuid(),ActorId=actor?.ToString()??"staff",Role=Roles.Administrator,Action="STAFF_UPDATED",Entity="StaffUser",EntityId=s.Id.ToString()});await db.SaveChangesAsync();await tx.CommitAsync();return Results.Ok(new{s.Id,s.Name,s.Phone,s.Role,s.IsActive,s.CreatedAt});}).RequireAuthorization(p=>p.RequireRole(Roles.Administrator));
 }
}
public sealed class BootstrapAdminService(IServiceProvider services,IConfiguration cfg,ILogger<BootstrapAdminService> log):IHostedService{
 public async Task StartAsync(CancellationToken ct){var phone=cfg["BootstrapAdmin:Phone"];var password=cfg["BootstrapAdmin:Password"];if(string.IsNullOrWhiteSpace(phone)||string.IsNullOrWhiteSpace(password))return;await using var scope=services.CreateAsyncScope();var db=scope.ServiceProvider.GetRequiredService<DadoDbContext>();if(await db.StaffUsers.AnyAsync(ct))return;var passwords=scope.ServiceProvider.GetRequiredService<PasswordService>();var name=cfg["BootstrapAdmin:Name"]?.Trim();var admin=new StaffUser{Id=Guid.NewGuid(),Name=string.IsNullOrWhiteSpace(name)?"Первый администратор":name,Phone=phone.Trim(),Role=Roles.Administrator,PasswordHash=passwords.Hash(password),IsActive=true};db.StaffUsers.Add(admin);db.AuditLogs.Add(new AuditLog{Id=Guid.NewGuid(),ActorId="bootstrap",Role=Roles.Administrator,Action="BOOTSTRAP_ADMIN_CREATED",Entity="StaffUser",EntityId=admin.Id.ToString()});await db.SaveChangesAsync(ct);log.LogInformation("Bootstrap administrator created from environment/configuration.");}
 public Task StopAsync(CancellationToken ct)=>Task.CompletedTask;
}


