import 'package:flutter/material.dart';
import 'catalog.dart';

class CartItem { final Product product; final String size,color; int quantity; CartItem(this.product,this.size,this.color,{this.quantity=1}); double get total=>product.price*quantity; }
class CartStore extends ChangeNotifier { CartStore._(); static final instance=CartStore._(); final List<CartItem> items=[]; void add(Product p,String s,String c){final i=items.indexWhere((x)=>x.product.name==p.name&&x.size==s&&x.color==c);if(i>=0){items[i].quantity++;}else{items.add(CartItem(p,s,c));}notifyListeners();} void change(CartItem x,int d){x.quantity+=d;if(x.quantity<=0)items.remove(x);notifyListeners();} void remove(CartItem x){items.remove(x);notifyListeners();} double get subtotal=>items.fold(0,(s,x)=>s+x.total); void clear(){items.clear();notifyListeners();}}

class CartPage extends StatelessWidget {const CartPage({super.key});@override Widget build(BuildContext context)=>SafeArea(child:AnimatedBuilder(animation:CartStore.instance,builder:(context,_){final c=CartStore.instance;if(c.items.isEmpty)return const Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.shopping_cart_outlined,size:70,color:Colors.black38),SizedBox(height:12),Text('Корзина пуста',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),Text('Добавьте товары из каталога')]));return Column(children:[const Padding(padding:EdgeInsets.all(16),child:Align(alignment:Alignment.centerLeft,child:Text('Корзина',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold)))),Expanded(child:ListView.builder(itemCount:c.items.length,itemBuilder:(context,i){final x=c.items[i];return Card(margin:const EdgeInsets.symmetric(horizontal:12,vertical:5),child:ListTile(leading:Icon(x.product.icon),title:Text(x.product.name),subtitle:Text('${x.size} • ${x.color}\n${x.product.price.toStringAsFixed(0)} с.'),isThreeLine:true,trailing:SizedBox(width:116,child:Row(children:[IconButton(onPressed:()=>c.change(x,-1),icon:const Icon(Icons.remove_circle_outline)),Text('${x.quantity}',style:const TextStyle(fontWeight:FontWeight.bold)),IconButton(onPressed:()=>c.change(x,1),icon:const Icon(Icons.add_circle_outline))]))); })),Padding(padding:const EdgeInsets.all(16),child:Column(children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('Итого',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),Text('${c.subtotal.toStringAsFixed(0)} сомони',style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900,color:dadoRed))]),const SizedBox(height:12),SizedBox(width:double.infinity,child:FilledButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const CheckoutPage())),child:const Padding(padding:EdgeInsets.all(14),child:Text('Оформить заказ'))))]))]);})) );}

class CheckoutPage extends StatefulWidget {const CheckoutPage({super.key});@override State<CheckoutPage> createState()=>_CheckoutPageState();}
class _CheckoutPageState extends State<CheckoutPage>{String delivery='Курьер';@override Widget build(BuildContext context){final sum=CartStore.instance.subtotal;return Scaffold(appBar:AppBar(title:const Text('Оформление заказа')),body:ListView(padding:const EdgeInsets.all(18),children:[const Text('Получение',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),RadioListTile(value:'Курьер',groupValue:delivery,onChanged:(v)=>setState(()=>delivery=v!),title:const Text('Доставка курьером')),RadioListTile(value:'Самовывоз',groupValue:delivery,onChanged:(v)=>setState(()=>delivery=v!),title:const Text('Самовывоз')),if(delivery=='Курьер')const TextField(decoration:InputDecoration(labelText:'Адрес доставки',prefixIcon:Icon(Icons.location_on_outlined),border:OutlineInputBorder())),const SizedBox(height:18),const TextField(decoration:InputDecoration(labelText:'Промокод',prefixIcon:Icon(Icons.local_offer_outlined),border:OutlineInputBorder())),const SizedBox(height:24),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('К оплате',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),Text('${sum.toStringAsFixed(0)} сомони',style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900,color:dadoRed))]),const SizedBox(height:16),FilledButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>PaymentPage(amount:sum))),child:const Padding(padding:EdgeInsets.all(14),child:Text('Продолжить к оплате')))]));}}

class PaymentPage extends StatefulWidget {final double amount;const PaymentPage({super.key,required this.amount});@override State<PaymentPage> createState()=>_PaymentPageState();}
class _PaymentPageState extends State<PaymentPage>{String method='DADO Wallet';@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Оплата')),body:ListView(padding:const EdgeInsets.all(18),children:[const Text('Способ оплаты',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),for(final m in ['DADO Wallet','Банковская карта','QR-оплата','Наличными'])RadioListTile(value:m,groupValue:method,onChanged:(v)=>setState(()=>method=v!),title:Text(m),subtitle:m=='Банковская карта'?const Text('Безопасная токенизация через платежного провайдера'):null),const SizedBox(height:18),FilledButton(onPressed:(){CartStore.instance.clear();Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>const OrderSuccessPage()),(r)=>r.isFirst);},child:Padding(padding:const EdgeInsets.all(14),child:Text('Оплатить ${widget.amount.toStringAsFixed(0)} сомони'))),const SizedBox(height:10),const Text('Демо-интерфейс: в production успешная оплата подтверждается сервером после проверки webhook платежного провайдера.',style:TextStyle(fontSize:12,color:Colors.black54))]));}
class OrderSuccessPage extends StatelessWidget {const OrderSuccessPage({super.key});@override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.check_circle,size:90,color:Colors.green),const SizedBox(height:16),const Text('Заказ оформлен',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold)),const SizedBox(height:8),const Text('После подтверждения оплаты заказ появится в разделе «Мои заказы».',textAlign:TextAlign.center),const SizedBox(height:20),FilledButton(onPressed:()=>Navigator.pop(context),child:const Text('Готово'))])))));}
