import 'package:flutter/material.dart';
import 'api.dart';
import 'cart.dart';
const dadoRed=Color(0xFFE30613);
class Product{final String id,name,category,description;final double price;final List<String> sizes,colors;final IconData icon;const Product(this.id,this.name,this.category,this.price,this.description,this.sizes,this.colors,this.icon);factory Product.fromJson(Map<String,dynamic> j)=>Product(j['id']?.toString()??'',j['name']??'',j['category']??'Товары для дома',(j['price'] as num?)?.toDouble()??0,j['description']??'',const['Стандарт'],const['Стандарт'],Icons.inventory_2_outlined);}
class CatalogPage extends StatefulWidget{const CatalogPage({super.key});@override State<CatalogPage> createState()=>_CatalogPageState();}
class _CatalogPageState extends State<CatalogPage>{String query='';late Future<List<Product>> future;@override void initState(){super.initState();future=_load();}Future<List<Product>> _load()async=>(await ApiClient.instance.products()).map((x)=>Product.fromJson(x)).toList();@override Widget build(BuildContext context)=>SafeArea(child:Column(children:[Padding(padding:const EdgeInsets.fromLTRB(16,16,16,8),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Товары для дома',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold)),const SizedBox(height:12),TextField(onChanged:(v)=>setState(()=>query=v),decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'Найти товар',border:OutlineInputBorder()))])),Expanded(child:FutureBuilder<List<Product>>(future:future,builder:(context,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(s.hasError)return Center(child:Column(mainAxisSize:MainAxisSize.min,children:[const Text('Не удалось загрузить каталог'),TextButton(onPressed:()=>setState(()=>future=_load()),child:const Text('Повторить'))]));final items=(s.data??[]).where((p)=>p.name.toLowerCase().contains(query.toLowerCase())).toList();if(items.isEmpty)return const Center(child:Text('Товары пока не добавлены'));return GridView.builder(padding:const EdgeInsets.all(12),gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,childAspectRatio:.68,crossAxisSpacing:10,mainAxisSpacing:10),itemCount:items.length,itemBuilder:(context,i)=>ProductCard(product:items[i]));}))]));}
class ProductCard extends StatelessWidget{final Product product;const ProductCard({super.key,required this.product});@override Widget build(BuildContext context)=>Card(clipBehavior:Clip.antiAlias,child:InkWell(onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>ProductDetails(product:product))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:Container(color:const Color(0xFFF1F1F1),alignment:Alignment.center,child:Icon(product.icon,size:72,color:Colors.black54))),Padding(padding:const EdgeInsets.all(10),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(product.name,maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w600)),Text('${product.price.toStringAsFixed(0)} с.',style:const TextStyle(fontSize:18,fontWeight:FontWeight.w800,color:dadoRed)),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:()=>CartStore.instance.add(product,product.sizes.first,product.colors.first),icon:const Icon(Icons.add_shopping_cart,size:18),label:const Text('В корзину')))]))])));}
class ProductDetails extends StatefulWidget{final Product product;const ProductDetails({super.key,required this.product});@override State<ProductDetails> createState()=>_ProductDetailsState();}class _ProductDetailsState extends State<ProductDetails>{int size=0,color=0;@override Widget build(BuildContext context){final p=widget.product;return Scaffold(appBar:AppBar(title:Text(p.name)),body:ListView(padding:const EdgeInsets.all(18),children:[Container(height:260,color:const Color(0xFFF2F2F2),child:Icon(p.icon,size:130)),const SizedBox(height:18),Text(p.name,style:const TextStyle(fontSize:27,fontWeight:FontWeight.bold)),Text('${p.price.toStringAsFixed(0)} сомони',style:const TextStyle(fontSize:25,fontWeight:FontWeight.w900,color:dadoRed)),const SizedBox(height:16),Text(p.description),const SizedBox(height:20),FilledButton.icon(onPressed:()=>CartStore.instance.add(p,p.sizes[size],p.colors[color]),icon:const Icon(Icons.shopping_cart),label:const Text('Добавить в корзину'))]));}}
