using System;using DadoHome.Api.Data;using Microsoft.EntityFrameworkCore.Infrastructure;using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable
namespace DadoHome.Api.Migrations;
[DbContext(typeof(DadoDbContext))][Migration("20260923110000_InitialCreate")]
public partial class InitialCreate:Migration{
 protected override void Up(MigrationBuilder m){
  m.CreateTable("AuditLogs",t=>new{Id=t.Column<Guid>(type:"uuid",nullable:false),ActorId=t.Column<string>(type:"text",nullable:false),Role=t.Column<string>(type:"text",nullable:false),Action=t.Column<string>(type:"text",nullable:false),Entity=t.Column<string>(type:"text",nullable:false),EntityId=t.Column<string>(type:"text",nullable:false),CreatedAt=t.Column<DateTime>(type:"timestamp with time zone",nullable:false)},constraints:c=>c.PrimaryKey("PK_AuditLogs",x=>x.Id));
  m.CreateTable("Categories",t=>new{Id=t.Column<Guid>(type:"uuid",nullable:false),ParentId=t.Column<Guid>(type:"uuid",nullable:true),Name=t.Column<string>(type:"text",nullable:false),SortOrder=t.Column<int>(type:"integer",nullable:false),IsActive=t.Column<bool>(type:"boolean",nullable:false),CreatedAt=t.Column<DateTime>(type:"timestamp with time zone",nullable:false)},constraints:c=>c.PrimaryKey("PK_Categories",x=>x.Id));
  m.CreateTable("Customers",t=>new{Id=t.Column<Guid>(type:"uuid",nullable:false),Phone=t.Column<string>(type:"text",nullable:false),Name=t.Column<string>(type:"text",nullable:true),TwoFactorEnabled=t.Column<bool>(type:"boolean",nullable:false),CreatedAt=t.Column<DateTime>(type:"timestamp with time zone",nullable:false)},constraints:c=>c.PrimaryKey("PK_Customers",x=>x.Id));
  m.CreateTable("OrderItems",t=>new{Id=t.Column<Guid>(type:"uuid",nullable:false),OrderId=t.Column<Guid>(type:"uuid",nullable:false),ProductId=t.Column<Guid>(type:"uuid",nullable:false),ProductName=t.Column<string>(type:"text",nullable:false),Variant=t.Column<string>(type:"text",nullable:false),Quantity=t.Column<int>(type:"integer",nullable:false),ReturnedQuantity=t.Column<int>(type:"integer",nullable:false),UnitPrice=t.Column<decimal>(type:"numeric(18,2)",nullable:false)},constraints:c=>c.PrimaryKey("PK_OrderItems",x=>x.Id));
  m.CreateTable("Orders",t=>new{Id=t.Column<Guid>(type:"uuid",nullable:false),CustomerId=t.Column<Guid>(type:"uuid",nullable:false),Number=t.Column<string>(type:"text",nullable:false),Status=t.Column<string>(type:"text",nullable:false),StockState=t.Column<string>(type:"text",nullable:false),StockCommittedAt=t.Column<DateTime>(type:"timestamp with time zone",nullable:true),StockReleasedAt=t.Column<DateTime>(type:"timestamp with time zone",nullable:true),DeliveryMethod=t.Column<string>(type:"text",nullable:false),RecipientName=t.Column<string>(type:"text",nullable:false),RecipientPhone=t.Column<string>(type:"text",nullable:false),DeliveryAddress=t.Column<string>(type:"text",nullable:false),DeliveryComment=t.Column<string>(type:"text",nullable:false),Subtotal=t.Column<decimal>(type:"numeric(18,2)",nullable:false),DeliveryFee=t.Column<decimal>(type:"numeric(18,2)",nullable:false),PaymentMethod=t.Column<string>(type:"text",nullable:false),Total=t.Column<decimal>(type:"numeric(18,2)",nullable:false),CreatedAt=t.Column<DateTime>(type:"timestamp with time zone",nullable:false)},constraints:c=>c.PrimaryKey("PK_Orders",x=>x.Id));
  m.CreateTable("PaymentEvents",t=>new{Id=t.Column<Guid>(type:"uuid",nullable:false),EventId=t.Column<string>(type:"text",nullable:false),PaymentId=t.Column<Guid>(type:"uuid",nullable:false),Status=t.Column<string>(type:"text",nullable:false),CreatedAt=t.Column<DateTime>(type:"timestamp with time zone",nullable:false)},constraints:c=>c.PrimaryKey("PK_PaymentEvents",x=>x.Id));
  m.CreateTable("Payments",t=>new{Id=t.Column<Guid>(type:"uuid",nullable:false),OrderId=t.Column<Guid>(type:"uuid",nullable:false),CustomerId=t.Column<Guid>(type:"uuid",nullable:false),Amount=t.Column<decimal>(type:"numeric(18,2)",nullable:false),Method=t.Column<string>(type:"text",nullable:false),Provider=t.Column<string>(type:"text",nullable:false),Status=t.Column<string>(type:"text",nullable:false),ProviderTransactionId=t.Column<string>(type:"text",nullable:false),CreatedAt=t.Column<DateTime>(type:"timestamp with time zone",nullable:false)},constraints:c=>c.PrimaryKey("PK_Payments",x=>x.Id));
  m.CreateTable("ProductReturns",t=>new{Id=t.Column<Guid>(type:"uuid",nullable:false),OrderId=t.Column<Guid>(type:"uuid",nullable:false),OrderItemId=t.Column<Guid>(type:"uuid",nullable:false),ProductId=t.Column<Guid>(type:"uuid",nullable:false),Quantity=t.Column<int>(type:"integer",nullable:false),Reason=t.Column<string>(type:"text",nullable:false),IdempotencyKey=t.Column<string>(type:"text",nullable:false),ActorId=t.Column<string>(type:"text",nullable:false),CreatedAt=t.Column<DateTime>(type:"timestamp with time zone",nullable:false)},constraints:c=>c.PrimaryKey("PK_ProductReturns",x=>x.Id));
  m.CreateTable("Products",t=>new{Id=t.Column<Guid>(type:"uuid",nullable:false),Name=t.Column<string>(type:"text",nullable:false),Category=t.Column<string>(type:"text",nullable:false),CategoryId=t.Column<Guid>(type:"uuid",nullable:true),Description=t.Column<string>(type:"text",nullable:false),ImageUrl=t.Column<string>(type:"text",nullable:false),Sizes=t.Column<string>(type:"text",nullable:false),Colors=t.Column<string>(type:"text",nullable:false),Price=t.Column<decimal>(type:"numeric(18,2)",nullable:false),Stock=t.Column<int>(type:"integer",nullable:false),IsActive=t.Column<bool>(type:"boolean",nullable:false),CreatedAt=t.Column<DateTime>(type:"timestamp with time zone",nullable:false)},constraints:c=>c.PrimaryKey("PK_Products",x=>x.Id));
  m.CreateTable("Refunds",t=>new{Id=t.Column<Guid>(type:"uuid",nullable:false),PaymentId=t.Column<Guid>(type:"uuid",nullable:false),Amount=t.Column<decimal>(type:"numeric(18,2)",nullable:false),Reason=t.Column<string>(type:"text",nullable:false),Status=t.Column<string>(type:"text",nullable:false),CreatedAt=t.Column<DateTime>(type:"timestamp with time zone",nullable:false)},constraints:c=>c.PrimaryKey("PK_Refunds",x=>x.Id));
  m.CreateTable("StaffUsers",t=>new{Id=t.Column<Guid>(type:"uuid",nullable:false),Phone=t.Column<string>(type:"text",nullable:false),Name=t.Column<string>(type:"text",nullable:false),Role=t.Column<string>(type:"text",nullable:false),PasswordHash=t.Column<string>(type:"text",nullable:false),IsActive=t.Column<bool>(type:"boolean",nullable:false),CreatedAt=t.Column<DateTime>(type:"timestamp with time zone",nullable:false)},constraints:c=>c.PrimaryKey("PK_StaffUsers",x=>x.Id));
  m.CreateTable("WalletEntries",t=>new{Id=t.Column<Guid>(type:"uuid",nullable:false),WalletId=t.Column<Guid>(type:"uuid",nullable:false),OrderId=t.Column<Guid>(type:"uuid",nullable:true),Amount=t.Column<decimal>(type:"numeric(18,2)",nullable:false),Type=t.Column<string>(type:"text",nullable:false),Status=t.Column<string>(type:"text",nullable:false),ExternalId=t.Column<string>(type:"text",nullable:false),CreatedAt=t.Column<DateTime>(type:"timestamp with time zone",nullable:false)},constraints:c=>c.PrimaryKey("PK_WalletEntries",x=>x.Id));
  m.CreateTable("Wallets",t=>new{Id=t.Column<Guid>(type:"uuid",nullable:false),CustomerId=t.Column<Guid>(type:"uuid",nullable:false),Currency=t.Column<string>(type:"text",nullable:false),CreatedAt=t.Column<DateTime>(type:"timestamp with time zone",nullable:false)},constraints:c=>c.PrimaryKey("PK_Wallets",x=>x.Id));
  m.CreateIndex("IX_Categories_ParentId_Name","Categories",new[]{"ParentId","Name"},unique:true);m.CreateIndex("IX_Customers_Phone","Customers","Phone",unique:true);m.CreateIndex("IX_PaymentEvents_EventId","PaymentEvents","EventId",unique:true);m.CreateIndex("IX_ProductReturns_IdempotencyKey","ProductReturns","IdempotencyKey",unique:true);m.CreateIndex("IX_StaffUsers_Phone","StaffUsers","Phone",unique:true);m.CreateIndex("IX_WalletEntries_ExternalId","WalletEntries","ExternalId",unique:true);m.CreateIndex("IX_Wallets_CustomerId","Wallets","CustomerId",unique:true);
 }
 protected override void Down(MigrationBuilder m){m.DropTable("AuditLogs");m.DropTable("Categories");m.DropTable("Customers");m.DropTable("OrderItems");m.DropTable("Orders");m.DropTable("PaymentEvents");m.DropTable("Payments");m.DropTable("ProductReturns");m.DropTable("Products");m.DropTable("Refunds");m.DropTable("StaffUsers");m.DropTable("WalletEntries");m.DropTable("Wallets");}
}

