using System.Security.Cryptography;
using System.Text;
using DadoHome.Api.Data;
using Microsoft.EntityFrameworkCore;
namespace DadoHome.Api.Payments;
public record PaymentIntentRequest(Guid OrderId,string Method);
public record PaymentWebhook(string EventId,Guid PaymentId,string Status,string ProviderTransactionId);
public record RefundRequest(Guid PaymentId,decimal Amount,string Reason);
public class PaymentService(DadoDbContext db,IConfiguration cfg){
 public async Task<Payment> CreateIntent(Guid customerId,PaymentIntentRequest r){var order=await db.Orders.SingleAsync(x=>x.Id==r.OrderId&&x.CustomerId==customerId);if(order.Status!="Created"||order.StockState!="Reserved")throw new InvalidOperationException("OrderNotPayable");var existing=await db.Payments.OrderByDescending(x=>x.CreatedAt).FirstOrDefaultAsync(x=>x.OrderId==order.Id&&x.Status=="Pending");if(existing is not null)return existing;var p=new Payment{Id=Guid.NewGuid(),OrderId=order.Id,CustomerId=customerId,Amount=order.Total,Method=r.Method,Status="Pending",Provider="TBD",CreatedAt=DateTime.UtcNow};db.Payments.Add(p);await db.SaveChangesAsync();return p;}
 public bool VerifyWebhook(string body,string signature){var secret=cfg["Payments:WebhookSecret"]??"";if(string.IsNullOrEmpty(secret))return false;try{var hash=HMACSHA256.HashData(Encoding.UTF8.GetBytes(secret),Encoding.UTF8.GetBytes(body));return CryptographicOperations.FixedTimeEquals(hash,Convert.FromHexString(signature));}catch(FormatException){return false;}}
 public async Task<bool> ApplyWebhook(PaymentWebhook e){if(await db.PaymentEvents.AnyAsync(x=>x.EventId==e.EventId))return true;var allowed=new[]{"Pending","Successful","Failed","Cancelled","Expired"};if(!allowed.Contains(e.Status,StringComparer.OrdinalIgnoreCase))return false;await using var tx=await db.Database.BeginTransactionAsync(System.Data.IsolationLevel.Serializable);var p=await db.Payments.SingleOrDefaultAsync(x=>x.Id==e.PaymentId);if(p is null)return false;var order=await db.Orders.SingleAsync(x=>x.Id==p.OrderId);db.PaymentEvents.Add(new PaymentEvent{Id=Guid.NewGuid(),EventId=e.EventId,PaymentId=p.Id,Status=e.Status,CreatedAt=DateTime.UtcNow});p.ProviderTransactionId=e.ProviderTransactionId;p.Status=e.Status;
  if(e.Status.Equals("Successful",StringComparison.OrdinalIgnoreCase)&&order.StockState=="Reserved"){order.StockState="Committed";order.StockCommittedAt=DateTime.UtcNow;order.Status="Paid";db.AuditLogs.Add(new AuditLog{Id=Guid.NewGuid(),ActorId="payment-webhook",Role="System",Action="PAYMENT_SUCCESS_STOCK_COMMITTED",Entity="Order",EntityId=order.Id.ToString()});}
  else if((e.Status.Equals("Failed",StringComparison.OrdinalIgnoreCase)||e.Status.Equals("Cancelled",StringComparison.OrdinalIgnoreCase)||e.Status.Equals("Expired",StringComparison.OrdinalIgnoreCase))&&order.StockState=="Reserved"){var items=await db.OrderItems.Where(x=>x.OrderId==order.Id).ToListAsync();var ids=items.Select(x=>x.ProductId).Distinct().ToList();var products=await db.Products.Where(x=>ids.Contains(x.Id)).ToDictionaryAsync(x=>x.Id);foreach(var item in items)if(products.TryGetValue(item.ProductId,out var product))product.Stock+=Math.Max(0,item.Quantity-item.ReturnedQuantity);order.StockState="Released";order.StockReleasedAt=DateTime.UtcNow;order.Status="Cancelled";db.AuditLogs.Add(new AuditLog{Id=Guid.NewGuid(),ActorId="payment-webhook",Role="System",Action="PAYMENT_FAILED_STOCK_RELEASED",Entity="Order",EntityId=order.Id.ToString()});}
  await db.SaveChangesAsync();await tx.CommitAsync();return true;}
 public async Task<decimal> WalletBalance(Guid customerId){var w=await db.Wallets.SingleAsync(x=>x.CustomerId==customerId);return await db.WalletEntries.Where(x=>x.WalletId==w.Id&&x.Status=="Successful").SumAsync(x=>x.Amount);}
}
